### ISSUE TITLE
Uri string too long

### ISSUE THREAD

**Issue by danieljuvito** [GGG-KILLER/CSS-And-Js-Minifier#2]
![2017-07-24_18h41_04](https://user-images.githubusercontent.com/21116943/28522352-d47d3d02-70a1-11e7-81c1-9968d10ec94c.png)

**Comment by GGG-KILLER** [comment]
Which version of the program are you using?
What are the details of the crash?
What files were you trying to use this on?

**Comment by GGG-KILLER** [comment]
Closed by lack of information.
