### ISSUE TITLE
Combine files into a single

### ISSUE THREAD

**Issue by aissasell** [GGG-KILLER/CSS-And-Js-Minifier#3]
If only there were an option to select specific files and combine them into a single minified file.

**Comment by GGG-KILLER** [comment]
I'm sorry but this project isn't being worked on anymore.

I don't recommend usage of it (actually never did and never used this myself). This was more of a learning project than something I expected people to use.

A more usual approach using `gulp`, `grunt`, `webpack`, built-in framework systems or other available systems would be preferable to this tool.
